name: Build App Bundles
on:
  push:
    branches:
      - main

jobs:
  build_mac:
    name: Build macOS .app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust + macOS target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2

      # - uses: cargo-bins/cargo-binstall@main
      # - run: cargo binstall -y cargo-bundle
      - run: cargo install cargo-bundle

      - name: Build and bundle
        run: cargo bundle --release --format osx --target x86_64-apple-darwin

      - uses: actions/upload-artifact@v4
        with:
          name: DELTASAVER.app
          path: target/x86_64-apple-darwin/release/bundle/osx/DELTASAVER.app
  build_windows:
    name: Build Windows .exe
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Windows stuff
        run: brew install mingw-w64

      - name: Install Rust + macOS target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - uses: Swatinem/rust-cache@v2

      - name: Build and bundle
        run: cargo build --release --target x86_64-pc-windows-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: DELTASAVER.exe
          path: target/x86_64-pc-windows-gnu/release/deltasaver.exe
